[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "bash -c 'cd backend && alembic stamp head && echo STAMP_OK'"
healthcheckPath = "/health"
